### PR TITLE
added remarkable html options

### PR DESCRIPTION
**Pull request by davidpett**
removed wrapping element and added html options provided by remarkable

### CODE REVIEW

**Comment by johnotander** [comment]
Rad, thanks!

**Comment by johnotander** [comment]
Going to go ahead and bump the `ember-cli` version on this addon before releasing so it might take a bit (it's been a while :blush:). I'll let you know when I get the latest version published.

**Comment by davidpett** [comment]
let me know if i can help


*-DP*

**Comment by davidpett** [comment]
Reading further, these should probably have their own boolean, instead of relying on `html` since they are [syntax extensions](https://github.com/jonschlinkert/remarkable#syntax-extensions), thoughts? i can update if you agree

**Comment by johnotander** [comment]
Thanks! Just kicked off bumping the addon to the latest ember-cli.

Yeah, I definitely agree on the boolean front. That'd be wonderful if you wanted to update that!

**Comment by johnotander** [comment]
Dusted off the cobwebs and bumped ember-cli : ). Latest pushed to `ember-remarkable@3.0.0`. Please note I removed the `md` helper in favor of the component.

Let me know if you encounter any issues and thank you again!

**Comment by davidpett** [comment]
Sweet, I will test it out. I also used it on ember-fastboot.com and will update

**Comment by johnotander** [comment]
:dancers:

**Pull request merged**
