### PR TITLE
Allow renderding arbitrary Ember components, fixes #19

### LINKED ISSUE #19: Internal links (and possibly arbitrary components) in rendered HTML
Hi.

My markdown content has cross-references. I want them to behave like internal links between routes.

I think ember-remarkable could optionally run rendered HTML through Ember template compiler to leverage `{{link-to}}`s and other components.

Or maybe there's a better path?

### PR DESCRIPTION
**Pull request by lolmaus**
For details, please see the updated README: [rendered](https://github.com/lolmaus/ember-remarkable/tree/feature-dynamic-templates#dynamic-template-rendering).

### CODE REVIEW

**Comment by johnotander** [comment]
This is awesome! Thanks!

**Comment by lolmaus** [comment]
Tell me when this is released. ^_^

**Comment by johnotander** [comment]
Sure thing : ). Should be released momentarily. Just doing some digging to see why the test is failing for ember-beta.

**Comment by johnotander** [comment]
Got it fixed by tweaking the `{{link-to}}` call. Published to npm as `ember-remarkable@3.1.0`. Let me know if you encounter any issues, and thank you again! :beers: :beers: :beers: :beers:

**Comment by lolmaus** [comment]
:beers:

**Pull request merged**
